version: '2'

services:
  integration-test:
    build: .
    links:
      - user-test
    depends_on:
      - user-test
    networks:
      - testapp
  
  user-test:
    image: weaveworksdemos/user:0.4.4
    hostname: user-test
    restart: always
    ports:
      - "8080:80"
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    links:
      - user-db-test
    depends_on:
      - user-db-test
    environment:
      - MONGO_HOST=user-db-test:27017
    networks:
      - testapp
  user-db-test:
    image: weaveworksdemos/user-db:0.4.0
    hostname: user-db-test
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    # read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    networks:
      - testapp
networks:
  testapp:
    driver: bridge